#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.235
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SCR06DB")]
	public partial class SCR06DBDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertM_Color(M_Color instance);
    partial void UpdateM_Color(M_Color instance);
    partial void DeleteM_Color(M_Color instance);
    partial void InsertM_ColorNo(M_ColorNo instance);
    partial void UpdateM_ColorNo(M_ColorNo instance);
    partial void DeleteM_ColorNo(M_ColorNo instance);
    partial void InsertM_WireSize(M_WireSize instance);
    partial void UpdateM_WireSize(M_WireSize instance);
    partial void DeleteM_WireSize(M_WireSize instance);
    partial void InsertM_WireType(M_WireType instance);
    partial void UpdateM_WireType(M_WireType instance);
    partial void DeleteM_WireType(M_WireType instance);
    partial void InsertM_WireDetail(M_WireDetail instance);
    partial void UpdateM_WireDetail(M_WireDetail instance);
    partial void DeleteM_WireDetail(M_WireDetail instance);
    partial void InsertL_Work(L_Work instance);
    partial void UpdateL_Work(L_Work instance);
    partial void DeleteL_Work(L_Work instance);
    partial void InsertM_Quality(M_Quality instance);
    partial void UpdateM_Quality(M_Quality instance);
    partial void DeleteM_Quality(M_Quality instance);
    partial void InsertR_Quality(R_Quality instance);
    partial void UpdateR_Quality(R_Quality instance);
    partial void DeleteR_Quality(R_Quality instance);
    partial void InsertM_Section(M_Section instance);
    partial void UpdateM_Section(M_Section instance);
    partial void DeleteM_Section(M_Section instance);
    partial void InsertM_GuideBlade(M_GuideBlade instance);
    partial void UpdateM_GuideBlade(M_GuideBlade instance);
    partial void DeleteM_GuideBlade(M_GuideBlade instance);
    partial void InsertD_Work(D_Work instance);
    partial void UpdateD_Work(D_Work instance);
    partial void DeleteD_Work(D_Work instance);
    partial void InsertT_Operator(T_Operator instance);
    partial void UpdateT_Operator(T_Operator instance);
    partial void DeleteT_Operator(T_Operator instance);
    partial void InsertR_Work(R_Work instance);
    partial void UpdateR_Work(R_Work instance);
    partial void DeleteR_Work(R_Work instance);
    partial void InsertM_Operator(M_Operator instance);
    partial void UpdateM_Operator(M_Operator instance);
    partial void DeleteM_Operator(M_Operator instance);
    #endregion
		
		public SCR06DBDataClassesDataContext() : 
				base(global::Alchemist.Properties.Settings.Default.SCR06DBConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public SCR06DBDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SCR06DBDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SCR06DBDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SCR06DBDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<M_Color> M_Color
		{
			get
			{
				return this.GetTable<M_Color>();
			}
		}
		
		public System.Data.Linq.Table<M_ColorNo> M_ColorNo
		{
			get
			{
				return this.GetTable<M_ColorNo>();
			}
		}
		
		public System.Data.Linq.Table<M_WireSize> M_WireSize
		{
			get
			{
				return this.GetTable<M_WireSize>();
			}
		}
		
		public System.Data.Linq.Table<M_WireType> M_WireType
		{
			get
			{
				return this.GetTable<M_WireType>();
			}
		}
		
		public System.Data.Linq.Table<M_WireDetail> M_WireDetail
		{
			get
			{
				return this.GetTable<M_WireDetail>();
			}
		}
		
		public System.Data.Linq.Table<L_Work> L_Work
		{
			get
			{
				return this.GetTable<L_Work>();
			}
		}
		
		public System.Data.Linq.Table<M_Quality> M_Quality
		{
			get
			{
				return this.GetTable<M_Quality>();
			}
		}
		
		public System.Data.Linq.Table<R_Quality> R_Quality
		{
			get
			{
				return this.GetTable<R_Quality>();
			}
		}
		
		public System.Data.Linq.Table<M_Section> M_Section
		{
			get
			{
				return this.GetTable<M_Section>();
			}
		}
		
		public System.Data.Linq.Table<M_GuideBlade> M_GuideBlade
		{
			get
			{
				return this.GetTable<M_GuideBlade>();
			}
		}
		
		public System.Data.Linq.Table<D_Work> D_Work
		{
			get
			{
				return this.GetTable<D_Work>();
			}
		}
		
		public System.Data.Linq.Table<T_Operator> T_Operator
		{
			get
			{
				return this.GetTable<T_Operator>();
			}
		}
		
		public System.Data.Linq.Table<R_Work> R_Work
		{
			get
			{
				return this.GetTable<R_Work>();
			}
		}
		
		public System.Data.Linq.Table<M_Operator> M_Operator
		{
			get
			{
				return this.GetTable<M_Operator>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_Color")]
	public partial class M_Color : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ColorChar;
		
		private string _ColorCode;
		
		private string _ColorRGBCode;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnColorCharChanging(string value);
    partial void OnColorCharChanged();
    partial void OnColorCodeChanging(string value);
    partial void OnColorCodeChanged();
    partial void OnColorRGBCodeChanging(string value);
    partial void OnColorRGBCodeChanged();
    #endregion
		
		public M_Color()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorChar", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ColorChar
		{
			get
			{
				return this._ColorChar;
			}
			set
			{
				if ((this._ColorChar != value))
				{
					this.OnColorCharChanging(value);
					this.SendPropertyChanging();
					this._ColorChar = value;
					this.SendPropertyChanged("ColorChar");
					this.OnColorCharChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorCode", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string ColorCode
		{
			get
			{
				return this._ColorCode;
			}
			set
			{
				if ((this._ColorCode != value))
				{
					this.OnColorCodeChanging(value);
					this.SendPropertyChanging();
					this._ColorCode = value;
					this.SendPropertyChanged("ColorCode");
					this.OnColorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorRGBCode", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string ColorRGBCode
		{
			get
			{
				return this._ColorRGBCode;
			}
			set
			{
				if ((this._ColorRGBCode != value))
				{
					this.OnColorRGBCodeChanging(value);
					this.SendPropertyChanging();
					this._ColorRGBCode = value;
					this.SendPropertyChanged("ColorRGBCode");
					this.OnColorRGBCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_ColorNo")]
	public partial class M_ColorNo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ColorNo;
		
		private string _ColorNoCode;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnColorNoChanging(string value);
    partial void OnColorNoChanged();
    partial void OnColorNoCodeChanging(string value);
    partial void OnColorNoCodeChanged();
    #endregion
		
		public M_ColorNo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorNo", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ColorNo
		{
			get
			{
				return this._ColorNo;
			}
			set
			{
				if ((this._ColorNo != value))
				{
					this.OnColorNoChanging(value);
					this.SendPropertyChanging();
					this._ColorNo = value;
					this.SendPropertyChanged("ColorNo");
					this.OnColorNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorNoCode", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string ColorNoCode
		{
			get
			{
				return this._ColorNoCode;
			}
			set
			{
				if ((this._ColorNoCode != value))
				{
					this.OnColorNoCodeChanging(value);
					this.SendPropertyChanging();
					this._ColorNoCode = value;
					this.SendPropertyChanged("ColorNoCode");
					this.OnColorNoCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_WireSize")]
	public partial class M_WireSize : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WireSize;
		
		private string _WireSizeCode;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWireSizeChanging(string value);
    partial void OnWireSizeChanged();
    partial void OnWireSizeCodeChanging(string value);
    partial void OnWireSizeCodeChanged();
    #endregion
		
		public M_WireSize()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WireSize", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WireSize
		{
			get
			{
				return this._WireSize;
			}
			set
			{
				if ((this._WireSize != value))
				{
					this.OnWireSizeChanging(value);
					this.SendPropertyChanging();
					this._WireSize = value;
					this.SendPropertyChanged("WireSize");
					this.OnWireSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WireSizeCode", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string WireSizeCode
		{
			get
			{
				return this._WireSizeCode;
			}
			set
			{
				if ((this._WireSizeCode != value))
				{
					this.OnWireSizeCodeChanging(value);
					this.SendPropertyChanging();
					this._WireSizeCode = value;
					this.SendPropertyChanged("WireSizeCode");
					this.OnWireSizeCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_WireType")]
	public partial class M_WireType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WireType;
		
		private string _WireTypeCode;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWireTypeChanging(string value);
    partial void OnWireTypeChanged();
    partial void OnWireTypeCodeChanging(string value);
    partial void OnWireTypeCodeChanged();
    #endregion
		
		public M_WireType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WireType", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WireType
		{
			get
			{
				return this._WireType;
			}
			set
			{
				if ((this._WireType != value))
				{
					this.OnWireTypeChanging(value);
					this.SendPropertyChanging();
					this._WireType = value;
					this.SendPropertyChanged("WireType");
					this.OnWireTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WireTypeCode", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string WireTypeCode
		{
			get
			{
				return this._WireTypeCode;
			}
			set
			{
				if ((this._WireTypeCode != value))
				{
					this.OnWireTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._WireTypeCode = value;
					this.SendPropertyChanged("WireTypeCode");
					this.OnWireTypeCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_WireDetail")]
	public partial class M_WireDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Wire_Code;
		
		private string _Wire_Color;
		
		private int _Core_Num;
		
		private string _C_Col1_1;
		
		private string _C_Col1_2;
		
		private string _C_Col2_1;
		
		private string _C_Col2_2;
		
		private string _C_Col3_1;
		
		private string _C_Col3_2;
		
		private string _C_Col4_1;
		
		private string _C_Col4_2;
		
		private string _C_Col5_1;
		
		private string _C_Col5_2;
		
		private string _C_Col6_1;
		
		private string _C_Col6_2;
		
		private string _C_Col7_1;
		
		private string _C_Col7_2;
		
		private string _C_Col8_1;
		
		private string _C_Col8_2;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWire_CodeChanging(string value);
    partial void OnWire_CodeChanged();
    partial void OnWire_ColorChanging(string value);
    partial void OnWire_ColorChanged();
    partial void OnCore_NumChanging(int value);
    partial void OnCore_NumChanged();
    partial void OnC_Col1_1Changing(string value);
    partial void OnC_Col1_1Changed();
    partial void OnC_Col1_2Changing(string value);
    partial void OnC_Col1_2Changed();
    partial void OnC_Col2_1Changing(string value);
    partial void OnC_Col2_1Changed();
    partial void OnC_Col2_2Changing(string value);
    partial void OnC_Col2_2Changed();
    partial void OnC_Col3_1Changing(string value);
    partial void OnC_Col3_1Changed();
    partial void OnC_Col3_2Changing(string value);
    partial void OnC_Col3_2Changed();
    partial void OnC_Col4_1Changing(string value);
    partial void OnC_Col4_1Changed();
    partial void OnC_Col4_2Changing(string value);
    partial void OnC_Col4_2Changed();
    partial void OnC_Col5_1Changing(string value);
    partial void OnC_Col5_1Changed();
    partial void OnC_Col5_2Changing(string value);
    partial void OnC_Col5_2Changed();
    partial void OnC_Col6_1Changing(string value);
    partial void OnC_Col6_1Changed();
    partial void OnC_Col6_2Changing(string value);
    partial void OnC_Col6_2Changed();
    partial void OnC_Col7_1Changing(string value);
    partial void OnC_Col7_1Changed();
    partial void OnC_Col7_2Changing(string value);
    partial void OnC_Col7_2Changed();
    partial void OnC_Col8_1Changing(string value);
    partial void OnC_Col8_1Changed();
    partial void OnC_Col8_2Changing(string value);
    partial void OnC_Col8_2Changed();
    #endregion
		
		public M_WireDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wire_Code", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Wire_Code
		{
			get
			{
				return this._Wire_Code;
			}
			set
			{
				if ((this._Wire_Code != value))
				{
					this.OnWire_CodeChanging(value);
					this.SendPropertyChanging();
					this._Wire_Code = value;
					this.SendPropertyChanged("Wire_Code");
					this.OnWire_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wire_Color", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Wire_Color
		{
			get
			{
				return this._Wire_Color;
			}
			set
			{
				if ((this._Wire_Color != value))
				{
					this.OnWire_ColorChanging(value);
					this.SendPropertyChanging();
					this._Wire_Color = value;
					this.SendPropertyChanged("Wire_Color");
					this.OnWire_ColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Core_Num", DbType="Int NOT NULL")]
		public int Core_Num
		{
			get
			{
				return this._Core_Num;
			}
			set
			{
				if ((this._Core_Num != value))
				{
					this.OnCore_NumChanging(value);
					this.SendPropertyChanging();
					this._Core_Num = value;
					this.SendPropertyChanged("Core_Num");
					this.OnCore_NumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col1_1", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string C_Col1_1
		{
			get
			{
				return this._C_Col1_1;
			}
			set
			{
				if ((this._C_Col1_1 != value))
				{
					this.OnC_Col1_1Changing(value);
					this.SendPropertyChanging();
					this._C_Col1_1 = value;
					this.SendPropertyChanged("C_Col1_1");
					this.OnC_Col1_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col1_2", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string C_Col1_2
		{
			get
			{
				return this._C_Col1_2;
			}
			set
			{
				if ((this._C_Col1_2 != value))
				{
					this.OnC_Col1_2Changing(value);
					this.SendPropertyChanging();
					this._C_Col1_2 = value;
					this.SendPropertyChanged("C_Col1_2");
					this.OnC_Col1_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col2_1", DbType="VarChar(2)")]
		public string C_Col2_1
		{
			get
			{
				return this._C_Col2_1;
			}
			set
			{
				if ((this._C_Col2_1 != value))
				{
					this.OnC_Col2_1Changing(value);
					this.SendPropertyChanging();
					this._C_Col2_1 = value;
					this.SendPropertyChanged("C_Col2_1");
					this.OnC_Col2_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col2_2", DbType="VarChar(2)")]
		public string C_Col2_2
		{
			get
			{
				return this._C_Col2_2;
			}
			set
			{
				if ((this._C_Col2_2 != value))
				{
					this.OnC_Col2_2Changing(value);
					this.SendPropertyChanging();
					this._C_Col2_2 = value;
					this.SendPropertyChanged("C_Col2_2");
					this.OnC_Col2_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col3_1", DbType="VarChar(2)")]
		public string C_Col3_1
		{
			get
			{
				return this._C_Col3_1;
			}
			set
			{
				if ((this._C_Col3_1 != value))
				{
					this.OnC_Col3_1Changing(value);
					this.SendPropertyChanging();
					this._C_Col3_1 = value;
					this.SendPropertyChanged("C_Col3_1");
					this.OnC_Col3_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col3_2", DbType="VarChar(2)")]
		public string C_Col3_2
		{
			get
			{
				return this._C_Col3_2;
			}
			set
			{
				if ((this._C_Col3_2 != value))
				{
					this.OnC_Col3_2Changing(value);
					this.SendPropertyChanging();
					this._C_Col3_2 = value;
					this.SendPropertyChanged("C_Col3_2");
					this.OnC_Col3_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col4_1", DbType="VarChar(2)")]
		public string C_Col4_1
		{
			get
			{
				return this._C_Col4_1;
			}
			set
			{
				if ((this._C_Col4_1 != value))
				{
					this.OnC_Col4_1Changing(value);
					this.SendPropertyChanging();
					this._C_Col4_1 = value;
					this.SendPropertyChanged("C_Col4_1");
					this.OnC_Col4_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col4_2", DbType="VarChar(2)")]
		public string C_Col4_2
		{
			get
			{
				return this._C_Col4_2;
			}
			set
			{
				if ((this._C_Col4_2 != value))
				{
					this.OnC_Col4_2Changing(value);
					this.SendPropertyChanging();
					this._C_Col4_2 = value;
					this.SendPropertyChanged("C_Col4_2");
					this.OnC_Col4_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col5_1", DbType="VarChar(2)")]
		public string C_Col5_1
		{
			get
			{
				return this._C_Col5_1;
			}
			set
			{
				if ((this._C_Col5_1 != value))
				{
					this.OnC_Col5_1Changing(value);
					this.SendPropertyChanging();
					this._C_Col5_1 = value;
					this.SendPropertyChanged("C_Col5_1");
					this.OnC_Col5_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col5_2", DbType="VarChar(2)")]
		public string C_Col5_2
		{
			get
			{
				return this._C_Col5_2;
			}
			set
			{
				if ((this._C_Col5_2 != value))
				{
					this.OnC_Col5_2Changing(value);
					this.SendPropertyChanging();
					this._C_Col5_2 = value;
					this.SendPropertyChanged("C_Col5_2");
					this.OnC_Col5_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col6_1", DbType="VarChar(2)")]
		public string C_Col6_1
		{
			get
			{
				return this._C_Col6_1;
			}
			set
			{
				if ((this._C_Col6_1 != value))
				{
					this.OnC_Col6_1Changing(value);
					this.SendPropertyChanging();
					this._C_Col6_1 = value;
					this.SendPropertyChanged("C_Col6_1");
					this.OnC_Col6_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col6_2", DbType="VarChar(2)")]
		public string C_Col6_2
		{
			get
			{
				return this._C_Col6_2;
			}
			set
			{
				if ((this._C_Col6_2 != value))
				{
					this.OnC_Col6_2Changing(value);
					this.SendPropertyChanging();
					this._C_Col6_2 = value;
					this.SendPropertyChanged("C_Col6_2");
					this.OnC_Col6_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col7_1", DbType="VarChar(2)")]
		public string C_Col7_1
		{
			get
			{
				return this._C_Col7_1;
			}
			set
			{
				if ((this._C_Col7_1 != value))
				{
					this.OnC_Col7_1Changing(value);
					this.SendPropertyChanging();
					this._C_Col7_1 = value;
					this.SendPropertyChanged("C_Col7_1");
					this.OnC_Col7_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col7_2", DbType="VarChar(2)")]
		public string C_Col7_2
		{
			get
			{
				return this._C_Col7_2;
			}
			set
			{
				if ((this._C_Col7_2 != value))
				{
					this.OnC_Col7_2Changing(value);
					this.SendPropertyChanging();
					this._C_Col7_2 = value;
					this.SendPropertyChanged("C_Col7_2");
					this.OnC_Col7_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col8_1", DbType="VarChar(2)")]
		public string C_Col8_1
		{
			get
			{
				return this._C_Col8_1;
			}
			set
			{
				if ((this._C_Col8_1 != value))
				{
					this.OnC_Col8_1Changing(value);
					this.SendPropertyChanging();
					this._C_Col8_1 = value;
					this.SendPropertyChanged("C_Col8_1");
					this.OnC_Col8_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Col8_2", DbType="VarChar(2)")]
		public string C_Col8_2
		{
			get
			{
				return this._C_Col8_2;
			}
			set
			{
				if ((this._C_Col8_2 != value))
				{
					this.OnC_Col8_2Changing(value);
					this.SendPropertyChanging();
					this._C_Col8_2 = value;
					this.SendPropertyChanged("C_Col8_2");
					this.OnC_Col8_2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.L_Work")]
	public partial class L_Work : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Renban;
		
		private string _Densen_code;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRenbanChanging(string value);
    partial void OnRenbanChanged();
    partial void OnDensen_codeChanging(string value);
    partial void OnDensen_codeChanged();
    #endregion
		
		public L_Work()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Renban", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Renban
		{
			get
			{
				return this._Renban;
			}
			set
			{
				if ((this._Renban != value))
				{
					this.OnRenbanChanging(value);
					this.SendPropertyChanging();
					this._Renban = value;
					this.SendPropertyChanged("Renban");
					this.OnRenbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Densen_code", DbType="Char(10)")]
		public string Densen_code
		{
			get
			{
				return this._Densen_code;
			}
			set
			{
				if ((this._Densen_code != value))
				{
					this.OnDensen_codeChanging(value);
					this.SendPropertyChanging();
					this._Densen_code = value;
					this.SendPropertyChanged("Densen_code");
					this.OnDensen_codeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_Quality")]
	public partial class M_Quality : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QualityCode;
		
		private string _QualityItem;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQualityCodeChanging(int value);
    partial void OnQualityCodeChanged();
    partial void OnQualityItemChanging(string value);
    partial void OnQualityItemChanged();
    #endregion
		
		public M_Quality()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QualityCode", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int QualityCode
		{
			get
			{
				return this._QualityCode;
			}
			set
			{
				if ((this._QualityCode != value))
				{
					this.OnQualityCodeChanging(value);
					this.SendPropertyChanging();
					this._QualityCode = value;
					this.SendPropertyChanged("QualityCode");
					this.OnQualityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QualityItem", DbType="VarChar(30)")]
		public string QualityItem
		{
			get
			{
				return this._QualityItem;
			}
			set
			{
				if ((this._QualityItem != value))
				{
					this.OnQualityItemChanging(value);
					this.SendPropertyChanging();
					this._QualityItem = value;
					this.SendPropertyChanged("QualityItem");
					this.OnQualityItemChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.R_Quality")]
	public partial class R_Quality : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Renban;
		
		private System.DateTime _Date;
		
		private string _Item1;
		
		private System.Nullable<int> _Count1;
		
		private string _Item2;
		
		private System.Nullable<int> _Count2;
		
		private string _Item3;
		
		private System.Nullable<int> _Count3;
		
		private string _Item4;
		
		private System.Nullable<int> _Count4;
		
		private string _Item5;
		
		private System.Nullable<int> _Count5;
		
		private string _Item6;
		
		private System.Nullable<int> _Count6;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRenbanChanging(string value);
    partial void OnRenbanChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnItem1Changing(string value);
    partial void OnItem1Changed();
    partial void OnCount1Changing(System.Nullable<int> value);
    partial void OnCount1Changed();
    partial void OnItem2Changing(string value);
    partial void OnItem2Changed();
    partial void OnCount2Changing(System.Nullable<int> value);
    partial void OnCount2Changed();
    partial void OnItem3Changing(string value);
    partial void OnItem3Changed();
    partial void OnCount3Changing(System.Nullable<int> value);
    partial void OnCount3Changed();
    partial void OnItem4Changing(string value);
    partial void OnItem4Changed();
    partial void OnCount4Changing(System.Nullable<int> value);
    partial void OnCount4Changed();
    partial void OnItem5Changing(string value);
    partial void OnItem5Changed();
    partial void OnCount5Changing(System.Nullable<int> value);
    partial void OnCount5Changed();
    partial void OnItem6Changing(string value);
    partial void OnItem6Changed();
    partial void OnCount6Changing(System.Nullable<int> value);
    partial void OnCount6Changed();
    #endregion
		
		public R_Quality()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Renban", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Renban
		{
			get
			{
				return this._Renban;
			}
			set
			{
				if ((this._Renban != value))
				{
					this.OnRenbanChanging(value);
					this.SendPropertyChanging();
					this._Renban = value;
					this.SendPropertyChanged("Renban");
					this.OnRenbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item1", DbType="VarChar(30)")]
		public string Item1
		{
			get
			{
				return this._Item1;
			}
			set
			{
				if ((this._Item1 != value))
				{
					this.OnItem1Changing(value);
					this.SendPropertyChanging();
					this._Item1 = value;
					this.SendPropertyChanged("Item1");
					this.OnItem1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count1", DbType="Int")]
		public System.Nullable<int> Count1
		{
			get
			{
				return this._Count1;
			}
			set
			{
				if ((this._Count1 != value))
				{
					this.OnCount1Changing(value);
					this.SendPropertyChanging();
					this._Count1 = value;
					this.SendPropertyChanged("Count1");
					this.OnCount1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item2", DbType="VarChar(30)")]
		public string Item2
		{
			get
			{
				return this._Item2;
			}
			set
			{
				if ((this._Item2 != value))
				{
					this.OnItem2Changing(value);
					this.SendPropertyChanging();
					this._Item2 = value;
					this.SendPropertyChanged("Item2");
					this.OnItem2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count2", DbType="Int")]
		public System.Nullable<int> Count2
		{
			get
			{
				return this._Count2;
			}
			set
			{
				if ((this._Count2 != value))
				{
					this.OnCount2Changing(value);
					this.SendPropertyChanging();
					this._Count2 = value;
					this.SendPropertyChanged("Count2");
					this.OnCount2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item3", DbType="VarChar(30)")]
		public string Item3
		{
			get
			{
				return this._Item3;
			}
			set
			{
				if ((this._Item3 != value))
				{
					this.OnItem3Changing(value);
					this.SendPropertyChanging();
					this._Item3 = value;
					this.SendPropertyChanged("Item3");
					this.OnItem3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count3", DbType="Int")]
		public System.Nullable<int> Count3
		{
			get
			{
				return this._Count3;
			}
			set
			{
				if ((this._Count3 != value))
				{
					this.OnCount3Changing(value);
					this.SendPropertyChanging();
					this._Count3 = value;
					this.SendPropertyChanged("Count3");
					this.OnCount3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item4", DbType="VarChar(30)")]
		public string Item4
		{
			get
			{
				return this._Item4;
			}
			set
			{
				if ((this._Item4 != value))
				{
					this.OnItem4Changing(value);
					this.SendPropertyChanging();
					this._Item4 = value;
					this.SendPropertyChanged("Item4");
					this.OnItem4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count4", DbType="Int")]
		public System.Nullable<int> Count4
		{
			get
			{
				return this._Count4;
			}
			set
			{
				if ((this._Count4 != value))
				{
					this.OnCount4Changing(value);
					this.SendPropertyChanging();
					this._Count4 = value;
					this.SendPropertyChanged("Count4");
					this.OnCount4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item5", DbType="VarChar(30)")]
		public string Item5
		{
			get
			{
				return this._Item5;
			}
			set
			{
				if ((this._Item5 != value))
				{
					this.OnItem5Changing(value);
					this.SendPropertyChanging();
					this._Item5 = value;
					this.SendPropertyChanged("Item5");
					this.OnItem5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count5", DbType="Int")]
		public System.Nullable<int> Count5
		{
			get
			{
				return this._Count5;
			}
			set
			{
				if ((this._Count5 != value))
				{
					this.OnCount5Changing(value);
					this.SendPropertyChanging();
					this._Count5 = value;
					this.SendPropertyChanged("Count5");
					this.OnCount5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item6", DbType="VarChar(30)")]
		public string Item6
		{
			get
			{
				return this._Item6;
			}
			set
			{
				if ((this._Item6 != value))
				{
					this.OnItem6Changing(value);
					this.SendPropertyChanging();
					this._Item6 = value;
					this.SendPropertyChanged("Item6");
					this.OnItem6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count6", DbType="Int")]
		public System.Nullable<int> Count6
		{
			get
			{
				return this._Count6;
			}
			set
			{
				if ((this._Count6 != value))
				{
					this.OnCount6Changing(value);
					this.SendPropertyChanging();
					this._Count6 = value;
					this.SendPropertyChanged("Count6");
					this.OnCount6Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_Section")]
	public partial class M_Section : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SectionCode;
		
		private string _SectionName;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSectionCodeChanging(int value);
    partial void OnSectionCodeChanged();
    partial void OnSectionNameChanging(string value);
    partial void OnSectionNameChanged();
    #endregion
		
		public M_Section()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionCode", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SectionCode
		{
			get
			{
				return this._SectionCode;
			}
			set
			{
				if ((this._SectionCode != value))
				{
					this.OnSectionCodeChanging(value);
					this.SendPropertyChanging();
					this._SectionCode = value;
					this.SendPropertyChanged("SectionCode");
					this.OnSectionCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionName", DbType="VarChar(30)")]
		public string SectionName
		{
			get
			{
				return this._SectionName;
			}
			set
			{
				if ((this._SectionName != value))
				{
					this.OnSectionNameChanging(value);
					this.SendPropertyChanging();
					this._SectionName = value;
					this.SendPropertyChanged("SectionName");
					this.OnSectionNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_GuideBlade")]
	public partial class M_GuideBlade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WireType;
		
		private string _WireSize;
		
		private string _Guide1;
		
		private string _Guide2;
		
		private string _Blade;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWireTypeChanging(string value);
    partial void OnWireTypeChanged();
    partial void OnWireSizeChanging(string value);
    partial void OnWireSizeChanged();
    partial void OnGuide1Changing(string value);
    partial void OnGuide1Changed();
    partial void OnGuide2Changing(string value);
    partial void OnGuide2Changed();
    partial void OnBladeChanging(string value);
    partial void OnBladeChanged();
    #endregion
		
		public M_GuideBlade()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WireType", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WireType
		{
			get
			{
				return this._WireType;
			}
			set
			{
				if ((this._WireType != value))
				{
					this.OnWireTypeChanging(value);
					this.SendPropertyChanging();
					this._WireType = value;
					this.SendPropertyChanged("WireType");
					this.OnWireTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WireSize", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WireSize
		{
			get
			{
				return this._WireSize;
			}
			set
			{
				if ((this._WireSize != value))
				{
					this.OnWireSizeChanging(value);
					this.SendPropertyChanging();
					this._WireSize = value;
					this.SendPropertyChanged("WireSize");
					this.OnWireSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guide1", DbType="VarChar(10)")]
		public string Guide1
		{
			get
			{
				return this._Guide1;
			}
			set
			{
				if ((this._Guide1 != value))
				{
					this.OnGuide1Changing(value);
					this.SendPropertyChanging();
					this._Guide1 = value;
					this.SendPropertyChanged("Guide1");
					this.OnGuide1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guide2", DbType="VarChar(10)")]
		public string Guide2
		{
			get
			{
				return this._Guide2;
			}
			set
			{
				if ((this._Guide2 != value))
				{
					this.OnGuide2Changing(value);
					this.SendPropertyChanging();
					this._Guide2 = value;
					this.SendPropertyChanged("Guide2");
					this.OnGuide2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Blade", DbType="VarChar(10)")]
		public string Blade
		{
			get
			{
				return this._Blade;
			}
			set
			{
				if ((this._Blade != value))
				{
					this.OnBladeChanging(value);
					this.SendPropertyChanging();
					this._Blade = value;
					this.SendPropertyChanged("Blade");
					this.OnBladeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.D_Work")]
	public partial class D_Work : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Renban;
		
		private string _Hinban;
		
		private string _Seiban;
		
		private string _A_kairokigou;
		
		private string _B_kairokigou;
		
		private System.Nullable<int> _Setsu;
		
		private System.Nullable<int> _Tabadorisu;
		
		private System.Nullable<System.DateTime> _Dute1;
		
		private string _Sensyu;
		
		private string _Size;
		
		private string _Iro;
		
		private System.Nullable<int> _Setsudancho;
		
		private System.Nullable<double> _A_kawamukinagasa;
		
		private System.Nullable<double> _B_kawamukinagasa;
		
		private string _Densen_Code;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRenbanChanging(string value);
    partial void OnRenbanChanged();
    partial void OnHinbanChanging(string value);
    partial void OnHinbanChanged();
    partial void OnSeibanChanging(string value);
    partial void OnSeibanChanged();
    partial void OnA_kairokigouChanging(string value);
    partial void OnA_kairokigouChanged();
    partial void OnB_kairokigouChanging(string value);
    partial void OnB_kairokigouChanged();
    partial void OnSetsuChanging(System.Nullable<int> value);
    partial void OnSetsuChanged();
    partial void OnTabadorisuChanging(System.Nullable<int> value);
    partial void OnTabadorisuChanged();
    partial void OnDute1Changing(System.Nullable<System.DateTime> value);
    partial void OnDute1Changed();
    partial void OnSensyuChanging(string value);
    partial void OnSensyuChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnIroChanging(string value);
    partial void OnIroChanged();
    partial void OnSetsudanchoChanging(System.Nullable<int> value);
    partial void OnSetsudanchoChanged();
    partial void OnA_kawamukinagasaChanging(System.Nullable<double> value);
    partial void OnA_kawamukinagasaChanged();
    partial void OnB_kawamukinagasaChanging(System.Nullable<double> value);
    partial void OnB_kawamukinagasaChanged();
    partial void OnDensen_CodeChanging(string value);
    partial void OnDensen_CodeChanged();
    #endregion
		
		public D_Work()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Renban", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Renban
		{
			get
			{
				return this._Renban;
			}
			set
			{
				if ((this._Renban != value))
				{
					this.OnRenbanChanging(value);
					this.SendPropertyChanging();
					this._Renban = value;
					this.SendPropertyChanged("Renban");
					this.OnRenbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinban", DbType="Char(26)")]
		public string Hinban
		{
			get
			{
				return this._Hinban;
			}
			set
			{
				if ((this._Hinban != value))
				{
					this.OnHinbanChanging(value);
					this.SendPropertyChanging();
					this._Hinban = value;
					this.SendPropertyChanged("Hinban");
					this.OnHinbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seiban", DbType="Char(11)")]
		public string Seiban
		{
			get
			{
				return this._Seiban;
			}
			set
			{
				if ((this._Seiban != value))
				{
					this.OnSeibanChanging(value);
					this.SendPropertyChanging();
					this._Seiban = value;
					this.SendPropertyChanged("Seiban");
					this.OnSeibanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_kairokigou", DbType="Char(6)")]
		public string A_kairokigou
		{
			get
			{
				return this._A_kairokigou;
			}
			set
			{
				if ((this._A_kairokigou != value))
				{
					this.OnA_kairokigouChanging(value);
					this.SendPropertyChanging();
					this._A_kairokigou = value;
					this.SendPropertyChanged("A_kairokigou");
					this.OnA_kairokigouChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_kairokigou", DbType="Char(6)")]
		public string B_kairokigou
		{
			get
			{
				return this._B_kairokigou;
			}
			set
			{
				if ((this._B_kairokigou != value))
				{
					this.OnB_kairokigouChanging(value);
					this.SendPropertyChanging();
					this._B_kairokigou = value;
					this.SendPropertyChanged("B_kairokigou");
					this.OnB_kairokigouChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Setsu", DbType="Int")]
		public System.Nullable<int> Setsu
		{
			get
			{
				return this._Setsu;
			}
			set
			{
				if ((this._Setsu != value))
				{
					this.OnSetsuChanging(value);
					this.SendPropertyChanging();
					this._Setsu = value;
					this.SendPropertyChanged("Setsu");
					this.OnSetsuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tabadorisu", DbType="Int")]
		public System.Nullable<int> Tabadorisu
		{
			get
			{
				return this._Tabadorisu;
			}
			set
			{
				if ((this._Tabadorisu != value))
				{
					this.OnTabadorisuChanging(value);
					this.SendPropertyChanging();
					this._Tabadorisu = value;
					this.SendPropertyChanged("Tabadorisu");
					this.OnTabadorisuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dute1", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dute1
		{
			get
			{
				return this._Dute1;
			}
			set
			{
				if ((this._Dute1 != value))
				{
					this.OnDute1Changing(value);
					this.SendPropertyChanging();
					this._Dute1 = value;
					this.SendPropertyChanged("Dute1");
					this.OnDute1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sensyu", DbType="Char(5)")]
		public string Sensyu
		{
			get
			{
				return this._Sensyu;
			}
			set
			{
				if ((this._Sensyu != value))
				{
					this.OnSensyuChanging(value);
					this.SendPropertyChanging();
					this._Sensyu = value;
					this.SendPropertyChanged("Sensyu");
					this.OnSensyuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Char(6)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iro", DbType="Char(5)")]
		public string Iro
		{
			get
			{
				return this._Iro;
			}
			set
			{
				if ((this._Iro != value))
				{
					this.OnIroChanging(value);
					this.SendPropertyChanging();
					this._Iro = value;
					this.SendPropertyChanged("Iro");
					this.OnIroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Setsudancho", DbType="Int")]
		public System.Nullable<int> Setsudancho
		{
			get
			{
				return this._Setsudancho;
			}
			set
			{
				if ((this._Setsudancho != value))
				{
					this.OnSetsudanchoChanging(value);
					this.SendPropertyChanging();
					this._Setsudancho = value;
					this.SendPropertyChanged("Setsudancho");
					this.OnSetsudanchoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_kawamukinagasa", DbType="Float")]
		public System.Nullable<double> A_kawamukinagasa
		{
			get
			{
				return this._A_kawamukinagasa;
			}
			set
			{
				if ((this._A_kawamukinagasa != value))
				{
					this.OnA_kawamukinagasaChanging(value);
					this.SendPropertyChanging();
					this._A_kawamukinagasa = value;
					this.SendPropertyChanged("A_kawamukinagasa");
					this.OnA_kawamukinagasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_kawamukinagasa", DbType="Float")]
		public System.Nullable<double> B_kawamukinagasa
		{
			get
			{
				return this._B_kawamukinagasa;
			}
			set
			{
				if ((this._B_kawamukinagasa != value))
				{
					this.OnB_kawamukinagasaChanging(value);
					this.SendPropertyChanging();
					this._B_kawamukinagasa = value;
					this.SendPropertyChanged("B_kawamukinagasa");
					this.OnB_kawamukinagasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Densen_Code", DbType="Char(10)")]
		public string Densen_Code
		{
			get
			{
				return this._Densen_Code;
			}
			set
			{
				if ((this._Densen_Code != value))
				{
					this.OnDensen_CodeChanging(value);
					this.SendPropertyChanging();
					this._Densen_Code = value;
					this.SendPropertyChanged("Densen_Code");
					this.OnDensen_CodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Operator")]
	public partial class T_Operator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _OperatorCode;
		
		private string _OperatorName;
		
		private System.DateTime _WorkDate;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOperatorCodeChanging(string value);
    partial void OnOperatorCodeChanged();
    partial void OnOperatorNameChanging(string value);
    partial void OnOperatorNameChanged();
    partial void OnWorkDateChanging(System.DateTime value);
    partial void OnWorkDateChanged();
    #endregion
		
		public T_Operator()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorCode", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string OperatorCode
		{
			get
			{
				return this._OperatorCode;
			}
			set
			{
				if ((this._OperatorCode != value))
				{
					this.OnOperatorCodeChanging(value);
					this.SendPropertyChanging();
					this._OperatorCode = value;
					this.SendPropertyChanged("OperatorCode");
					this.OnOperatorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorName", DbType="VarChar(20)")]
		public string OperatorName
		{
			get
			{
				return this._OperatorName;
			}
			set
			{
				if ((this._OperatorName != value))
				{
					this.OnOperatorNameChanging(value);
					this.SendPropertyChanging();
					this._OperatorName = value;
					this.SendPropertyChanged("OperatorName");
					this.OnOperatorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkDate", DbType="DateTime NOT NULL")]
		public System.DateTime WorkDate
		{
			get
			{
				return this._WorkDate;
			}
			set
			{
				if ((this._WorkDate != value))
				{
					this.OnWorkDateChanging(value);
					this.SendPropertyChanging();
					this._WorkDate = value;
					this.SendPropertyChanged("WorkDate");
					this.OnWorkDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.R_Work")]
	public partial class R_Work : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Renban;
		
		private string _Hinban;
		
		private string _Seiban;
		
		private string _A_kairokigou;
		
		private string _B_kairokigou;
		
		private System.Nullable<int> _Setsu;
		
		private System.Nullable<int> _Tabadorisu;
		
		private System.Nullable<System.DateTime> _Dute1;
		
		private string _Sensyu;
		
		private string _Size;
		
		private string _Iro;
		
		private System.Nullable<int> _Setsudancho;
		
		private System.Nullable<double> _A_kawamukinagasa;
		
		private System.Nullable<double> _B_kawamukinagasa;
		
		private string _Densen_code;
		
		private string _Sagyosya_code;
		
		private string _Sagyosya_name;
		
		private System.Nullable<int> _Setsudancho_set;
		
		private System.Nullable<double> _A_kawamukinagasa_set;
		
		private System.Nullable<double> _B_kawamukinagasa_set;
		
		private System.Nullable<double> _A_hogushiryo_set;
		
		private System.Nullable<double> _B_hogushiryo_set;
		
		private System.Nullable<System.DateTime> _Kaishi_time;
		
		private System.Nullable<System.DateTime> _Syuryo_time;
		
		private System.Nullable<char> _AB_change;
		
		private System.Nullable<int> _Chudan_setsu;
		
		private System.Nullable<int> _Chudan_tabadorisu;
		
		private System.Nullable<char> _Sagyou_status;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRenbanChanging(string value);
    partial void OnRenbanChanged();
    partial void OnHinbanChanging(string value);
    partial void OnHinbanChanged();
    partial void OnSeibanChanging(string value);
    partial void OnSeibanChanged();
    partial void OnA_kairokigouChanging(string value);
    partial void OnA_kairokigouChanged();
    partial void OnB_kairokigouChanging(string value);
    partial void OnB_kairokigouChanged();
    partial void OnSetsuChanging(System.Nullable<int> value);
    partial void OnSetsuChanged();
    partial void OnTabadorisuChanging(System.Nullable<int> value);
    partial void OnTabadorisuChanged();
    partial void OnDute1Changing(System.Nullable<System.DateTime> value);
    partial void OnDute1Changed();
    partial void OnSensyuChanging(string value);
    partial void OnSensyuChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnIroChanging(string value);
    partial void OnIroChanged();
    partial void OnSetsudanchoChanging(System.Nullable<int> value);
    partial void OnSetsudanchoChanged();
    partial void OnA_kawamukinagasaChanging(System.Nullable<double> value);
    partial void OnA_kawamukinagasaChanged();
    partial void OnB_kawamukinagasaChanging(System.Nullable<double> value);
    partial void OnB_kawamukinagasaChanged();
    partial void OnDensen_codeChanging(string value);
    partial void OnDensen_codeChanged();
    partial void OnSagyosya_codeChanging(string value);
    partial void OnSagyosya_codeChanged();
    partial void OnSagyosya_nameChanging(string value);
    partial void OnSagyosya_nameChanged();
    partial void OnSetsudancho_setChanging(System.Nullable<int> value);
    partial void OnSetsudancho_setChanged();
    partial void OnA_kawamukinagasa_setChanging(System.Nullable<double> value);
    partial void OnA_kawamukinagasa_setChanged();
    partial void OnB_kawamukinagasa_setChanging(System.Nullable<double> value);
    partial void OnB_kawamukinagasa_setChanged();
    partial void OnA_hogushiryo_setChanging(System.Nullable<double> value);
    partial void OnA_hogushiryo_setChanged();
    partial void OnB_hogushiryo_setChanging(System.Nullable<double> value);
    partial void OnB_hogushiryo_setChanged();
    partial void OnKaishi_timeChanging(System.Nullable<System.DateTime> value);
    partial void OnKaishi_timeChanged();
    partial void OnSyuryo_timeChanging(System.Nullable<System.DateTime> value);
    partial void OnSyuryo_timeChanged();
    partial void OnAB_changeChanging(System.Nullable<char> value);
    partial void OnAB_changeChanged();
    partial void OnChudan_setsuChanging(System.Nullable<int> value);
    partial void OnChudan_setsuChanged();
    partial void OnChudan_tabadorisuChanging(System.Nullable<int> value);
    partial void OnChudan_tabadorisuChanged();
    partial void OnSagyou_statusChanging(System.Nullable<char> value);
    partial void OnSagyou_statusChanged();
    #endregion
		
		public R_Work()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Renban", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Renban
		{
			get
			{
				return this._Renban;
			}
			set
			{
				if ((this._Renban != value))
				{
					this.OnRenbanChanging(value);
					this.SendPropertyChanging();
					this._Renban = value;
					this.SendPropertyChanged("Renban");
					this.OnRenbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinban", DbType="Char(26)")]
		public string Hinban
		{
			get
			{
				return this._Hinban;
			}
			set
			{
				if ((this._Hinban != value))
				{
					this.OnHinbanChanging(value);
					this.SendPropertyChanging();
					this._Hinban = value;
					this.SendPropertyChanged("Hinban");
					this.OnHinbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seiban", DbType="Char(11)")]
		public string Seiban
		{
			get
			{
				return this._Seiban;
			}
			set
			{
				if ((this._Seiban != value))
				{
					this.OnSeibanChanging(value);
					this.SendPropertyChanging();
					this._Seiban = value;
					this.SendPropertyChanged("Seiban");
					this.OnSeibanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_kairokigou", DbType="Char(6)")]
		public string A_kairokigou
		{
			get
			{
				return this._A_kairokigou;
			}
			set
			{
				if ((this._A_kairokigou != value))
				{
					this.OnA_kairokigouChanging(value);
					this.SendPropertyChanging();
					this._A_kairokigou = value;
					this.SendPropertyChanged("A_kairokigou");
					this.OnA_kairokigouChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_kairokigou", DbType="Char(6)")]
		public string B_kairokigou
		{
			get
			{
				return this._B_kairokigou;
			}
			set
			{
				if ((this._B_kairokigou != value))
				{
					this.OnB_kairokigouChanging(value);
					this.SendPropertyChanging();
					this._B_kairokigou = value;
					this.SendPropertyChanged("B_kairokigou");
					this.OnB_kairokigouChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Setsu", DbType="Int")]
		public System.Nullable<int> Setsu
		{
			get
			{
				return this._Setsu;
			}
			set
			{
				if ((this._Setsu != value))
				{
					this.OnSetsuChanging(value);
					this.SendPropertyChanging();
					this._Setsu = value;
					this.SendPropertyChanged("Setsu");
					this.OnSetsuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tabadorisu", DbType="Int")]
		public System.Nullable<int> Tabadorisu
		{
			get
			{
				return this._Tabadorisu;
			}
			set
			{
				if ((this._Tabadorisu != value))
				{
					this.OnTabadorisuChanging(value);
					this.SendPropertyChanging();
					this._Tabadorisu = value;
					this.SendPropertyChanged("Tabadorisu");
					this.OnTabadorisuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dute1", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dute1
		{
			get
			{
				return this._Dute1;
			}
			set
			{
				if ((this._Dute1 != value))
				{
					this.OnDute1Changing(value);
					this.SendPropertyChanging();
					this._Dute1 = value;
					this.SendPropertyChanged("Dute1");
					this.OnDute1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sensyu", DbType="Char(5)")]
		public string Sensyu
		{
			get
			{
				return this._Sensyu;
			}
			set
			{
				if ((this._Sensyu != value))
				{
					this.OnSensyuChanging(value);
					this.SendPropertyChanging();
					this._Sensyu = value;
					this.SendPropertyChanged("Sensyu");
					this.OnSensyuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Char(6)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iro", DbType="Char(5)")]
		public string Iro
		{
			get
			{
				return this._Iro;
			}
			set
			{
				if ((this._Iro != value))
				{
					this.OnIroChanging(value);
					this.SendPropertyChanging();
					this._Iro = value;
					this.SendPropertyChanged("Iro");
					this.OnIroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Setsudancho", DbType="Int")]
		public System.Nullable<int> Setsudancho
		{
			get
			{
				return this._Setsudancho;
			}
			set
			{
				if ((this._Setsudancho != value))
				{
					this.OnSetsudanchoChanging(value);
					this.SendPropertyChanging();
					this._Setsudancho = value;
					this.SendPropertyChanged("Setsudancho");
					this.OnSetsudanchoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_kawamukinagasa", DbType="Float")]
		public System.Nullable<double> A_kawamukinagasa
		{
			get
			{
				return this._A_kawamukinagasa;
			}
			set
			{
				if ((this._A_kawamukinagasa != value))
				{
					this.OnA_kawamukinagasaChanging(value);
					this.SendPropertyChanging();
					this._A_kawamukinagasa = value;
					this.SendPropertyChanged("A_kawamukinagasa");
					this.OnA_kawamukinagasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_kawamukinagasa", DbType="Float")]
		public System.Nullable<double> B_kawamukinagasa
		{
			get
			{
				return this._B_kawamukinagasa;
			}
			set
			{
				if ((this._B_kawamukinagasa != value))
				{
					this.OnB_kawamukinagasaChanging(value);
					this.SendPropertyChanging();
					this._B_kawamukinagasa = value;
					this.SendPropertyChanged("B_kawamukinagasa");
					this.OnB_kawamukinagasaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Densen_code", DbType="Char(10)")]
		public string Densen_code
		{
			get
			{
				return this._Densen_code;
			}
			set
			{
				if ((this._Densen_code != value))
				{
					this.OnDensen_codeChanging(value);
					this.SendPropertyChanging();
					this._Densen_code = value;
					this.SendPropertyChanged("Densen_code");
					this.OnDensen_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sagyosya_code", DbType="VarChar(10)")]
		public string Sagyosya_code
		{
			get
			{
				return this._Sagyosya_code;
			}
			set
			{
				if ((this._Sagyosya_code != value))
				{
					this.OnSagyosya_codeChanging(value);
					this.SendPropertyChanging();
					this._Sagyosya_code = value;
					this.SendPropertyChanged("Sagyosya_code");
					this.OnSagyosya_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sagyosya_name", DbType="VarChar(20)")]
		public string Sagyosya_name
		{
			get
			{
				return this._Sagyosya_name;
			}
			set
			{
				if ((this._Sagyosya_name != value))
				{
					this.OnSagyosya_nameChanging(value);
					this.SendPropertyChanging();
					this._Sagyosya_name = value;
					this.SendPropertyChanged("Sagyosya_name");
					this.OnSagyosya_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Setsudancho_set", DbType="Int")]
		public System.Nullable<int> Setsudancho_set
		{
			get
			{
				return this._Setsudancho_set;
			}
			set
			{
				if ((this._Setsudancho_set != value))
				{
					this.OnSetsudancho_setChanging(value);
					this.SendPropertyChanging();
					this._Setsudancho_set = value;
					this.SendPropertyChanged("Setsudancho_set");
					this.OnSetsudancho_setChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_kawamukinagasa_set", DbType="Float")]
		public System.Nullable<double> A_kawamukinagasa_set
		{
			get
			{
				return this._A_kawamukinagasa_set;
			}
			set
			{
				if ((this._A_kawamukinagasa_set != value))
				{
					this.OnA_kawamukinagasa_setChanging(value);
					this.SendPropertyChanging();
					this._A_kawamukinagasa_set = value;
					this.SendPropertyChanged("A_kawamukinagasa_set");
					this.OnA_kawamukinagasa_setChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_kawamukinagasa_set", DbType="Float")]
		public System.Nullable<double> B_kawamukinagasa_set
		{
			get
			{
				return this._B_kawamukinagasa_set;
			}
			set
			{
				if ((this._B_kawamukinagasa_set != value))
				{
					this.OnB_kawamukinagasa_setChanging(value);
					this.SendPropertyChanging();
					this._B_kawamukinagasa_set = value;
					this.SendPropertyChanged("B_kawamukinagasa_set");
					this.OnB_kawamukinagasa_setChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_hogushiryo_set", DbType="Float")]
		public System.Nullable<double> A_hogushiryo_set
		{
			get
			{
				return this._A_hogushiryo_set;
			}
			set
			{
				if ((this._A_hogushiryo_set != value))
				{
					this.OnA_hogushiryo_setChanging(value);
					this.SendPropertyChanging();
					this._A_hogushiryo_set = value;
					this.SendPropertyChanged("A_hogushiryo_set");
					this.OnA_hogushiryo_setChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_hogushiryo_set", DbType="Float")]
		public System.Nullable<double> B_hogushiryo_set
		{
			get
			{
				return this._B_hogushiryo_set;
			}
			set
			{
				if ((this._B_hogushiryo_set != value))
				{
					this.OnB_hogushiryo_setChanging(value);
					this.SendPropertyChanging();
					this._B_hogushiryo_set = value;
					this.SendPropertyChanged("B_hogushiryo_set");
					this.OnB_hogushiryo_setChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaishi_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Kaishi_time
		{
			get
			{
				return this._Kaishi_time;
			}
			set
			{
				if ((this._Kaishi_time != value))
				{
					this.OnKaishi_timeChanging(value);
					this.SendPropertyChanging();
					this._Kaishi_time = value;
					this.SendPropertyChanged("Kaishi_time");
					this.OnKaishi_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Syuryo_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Syuryo_time
		{
			get
			{
				return this._Syuryo_time;
			}
			set
			{
				if ((this._Syuryo_time != value))
				{
					this.OnSyuryo_timeChanging(value);
					this.SendPropertyChanging();
					this._Syuryo_time = value;
					this.SendPropertyChanged("Syuryo_time");
					this.OnSyuryo_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AB_change", DbType="Char(1)")]
		public System.Nullable<char> AB_change
		{
			get
			{
				return this._AB_change;
			}
			set
			{
				if ((this._AB_change != value))
				{
					this.OnAB_changeChanging(value);
					this.SendPropertyChanging();
					this._AB_change = value;
					this.SendPropertyChanged("AB_change");
					this.OnAB_changeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chudan_setsu", DbType="Int")]
		public System.Nullable<int> Chudan_setsu
		{
			get
			{
				return this._Chudan_setsu;
			}
			set
			{
				if ((this._Chudan_setsu != value))
				{
					this.OnChudan_setsuChanging(value);
					this.SendPropertyChanging();
					this._Chudan_setsu = value;
					this.SendPropertyChanged("Chudan_setsu");
					this.OnChudan_setsuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chudan_tabadorisu", DbType="Int")]
		public System.Nullable<int> Chudan_tabadorisu
		{
			get
			{
				return this._Chudan_tabadorisu;
			}
			set
			{
				if ((this._Chudan_tabadorisu != value))
				{
					this.OnChudan_tabadorisuChanging(value);
					this.SendPropertyChanging();
					this._Chudan_tabadorisu = value;
					this.SendPropertyChanged("Chudan_tabadorisu");
					this.OnChudan_tabadorisuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sagyou_status", DbType="Char(1)")]
		public System.Nullable<char> Sagyou_status
		{
			get
			{
				return this._Sagyou_status;
			}
			set
			{
				if ((this._Sagyou_status != value))
				{
					this.OnSagyou_statusChanging(value);
					this.SendPropertyChanging();
					this._Sagyou_status = value;
					this.SendPropertyChanged("Sagyou_status");
					this.OnSagyou_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_Operator")]
	public partial class M_Operator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _OperatorCode;
		
		private string _OperatorName;
		
		private System.Nullable<int> _OperatorGroup;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOperatorCodeChanging(string value);
    partial void OnOperatorCodeChanged();
    partial void OnOperatorNameChanging(string value);
    partial void OnOperatorNameChanged();
    partial void OnOperatorGroupChanging(System.Nullable<int> value);
    partial void OnOperatorGroupChanged();
    #endregion
		
		public M_Operator()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorCode", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string OperatorCode
		{
			get
			{
				return this._OperatorCode;
			}
			set
			{
				if ((this._OperatorCode != value))
				{
					this.OnOperatorCodeChanging(value);
					this.SendPropertyChanging();
					this._OperatorCode = value;
					this.SendPropertyChanged("OperatorCode");
					this.OnOperatorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorName", DbType="VarChar(20)")]
		public string OperatorName
		{
			get
			{
				return this._OperatorName;
			}
			set
			{
				if ((this._OperatorName != value))
				{
					this.OnOperatorNameChanging(value);
					this.SendPropertyChanging();
					this._OperatorName = value;
					this.SendPropertyChanged("OperatorName");
					this.OnOperatorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorGroup", DbType="Int")]
		public System.Nullable<int> OperatorGroup
		{
			get
			{
				return this._OperatorGroup;
			}
			set
			{
				if ((this._OperatorGroup != value))
				{
					this.OnOperatorGroupChanging(value);
					this.SendPropertyChanging();
					this._OperatorGroup = value;
					this.SendPropertyChanged("OperatorGroup");
					this.OnOperatorGroupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
