//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CorrectDataMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorrectDataMsg() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.Properties.CorrectDataMsg", typeof(CorrectDataMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   端子無し運転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0101 {
            get {
                return ResourceManager.GetString("CORR_0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ﾍﾞﾙﾄｼｭｰﾀｰ動作長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0102 {
            get {
                return ResourceManager.GetString("CORR_0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ﾍﾞﾙﾄｼｭｰﾀｰ待ち時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0103 {
            get {
                return ResourceManager.GetString("CORR_0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   端子送り時間1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0104 {
            get {
                return ResourceManager.GetString("CORR_0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   端子送り時間2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0105 {
            get {
                return ResourceManager.GetString("CORR_0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空運転時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0106 {
            get {
                return ResourceManager.GetString("CORR_0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャリアカット1 回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0107 {
            get {
                return ResourceManager.GetString("CORR_0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャリアカット2 回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0108 {
            get {
                return ResourceManager.GetString("CORR_0108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着検出1 ファイバ/CFM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0109 {
            get {
                return ResourceManager.GetString("CORR_0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着検出2 ファイバ/CFM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_010A {
            get {
                return ResourceManager.GetString("CORR_010A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   判定終了後圧着1 無効/有効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_010B {
            get {
                return ResourceManager.GetString("CORR_010B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   判定終了後圧着2 無効/有効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_010C {
            get {
                return ResourceManager.GetString("CORR_010C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ1検出レベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_010D {
            get {
                return ResourceManager.GetString("CORR_010D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ1ティーチ回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_010E {
            get {
                return ResourceManager.GetString("CORR_010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ2検出レベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_010F {
            get {
                return ResourceManager.GetString("CORR_010F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ2ティーチ回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0110 {
            get {
                return ResourceManager.GetString("CORR_0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AUTOティーチフィード 有効/無効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0111 {
            get {
                return ResourceManager.GetString("CORR_0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ティーチ電線 不良品/良品 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0112 {
            get {
                return ResourceManager.GetString("CORR_0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AUTOストリップティーチ 有効/無効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0113 {
            get {
                return ResourceManager.GetString("CORR_0113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィード方式 CLOSE/OPEN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0114 {
            get {
                return ResourceManager.GetString("CORR_0114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ検出方式 導通/LAMS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0115 {
            get {
                return ResourceManager.GetString("CORR_0115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACH有無 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0116 {
            get {
                return ResourceManager.GetString("CORR_0116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LAMS機能選択 非防水/防水 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0117 {
            get {
                return ResourceManager.GetString("CORR_0117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トータルカウンタリセット有効/無効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0118 {
            get {
                return ResourceManager.GetString("CORR_0118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着カウンタリセット 有効/無効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0119 {
            get {
                return ResourceManager.GetString("CORR_0119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カウントタイプ Type1/Type2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_011A {
            get {
                return ResourceManager.GetString("CORR_011A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー電線長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0201 {
            get {
                return ResourceManager.GetString("CORR_0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テストモ－ド電線長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0202 {
            get {
                return ResourceManager.GetString("CORR_0202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サンプルモ－ド電線長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0203 {
            get {
                return ResourceManager.GetString("CORR_0203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスライン長さ[mm] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0204 {
            get {
                return ResourceManager.GetString("CORR_0204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電線継ぎ目送り出し長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0205 {
            get {
                return ResourceManager.GetString("CORR_0205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電線長さ補正値[+-mm] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0206 {
            get {
                return ResourceManager.GetString("CORR_0206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エアー吹き動作長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0207 {
            get {
                return ResourceManager.GetString("CORR_0207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スリップミス排出長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0208 {
            get {
                return ResourceManager.GetString("CORR_0208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テストフィード長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0209 {
            get {
                return ResourceManager.GetString("CORR_0209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックフィード長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_020A {
            get {
                return ResourceManager.GetString("CORR_020A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   過負荷電線排出長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_020B {
            get {
                return ResourceManager.GetString("CORR_020B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップフィード補正長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_020C {
            get {
                return ResourceManager.GetString("CORR_020C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.1旋回 原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0301 {
            get {
                return ResourceManager.GetString("CORR_0301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.1旋回 ストリップ位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0302 {
            get {
                return ResourceManager.GetString("CORR_0302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.1旋回 ストリップ検出位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0303 {
            get {
                return ResourceManager.GetString("CORR_0303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.1旋回 圧着位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0304 {
            get {
                return ResourceManager.GetString("CORR_0304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.1旋回 圧着退避位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0305 {
            get {
                return ResourceManager.GetString("CORR_0305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.1旋回 圧着検出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0306 {
            get {
                return ResourceManager.GetString("CORR_0306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.1旋回 速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0307 {
            get {
                return ResourceManager.GetString("CORR_0307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.1旋回 加速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0308 {
            get {
                return ResourceManager.GetString("CORR_0308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0401 {
            get {
                return ResourceManager.GetString("CORR_0401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 ストリップ位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0402 {
            get {
                return ResourceManager.GetString("CORR_0402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 ストリップ検出位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0403 {
            get {
                return ResourceManager.GetString("CORR_0403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 圧着位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0404 {
            get {
                return ResourceManager.GetString("CORR_0404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 圧着退避位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0405 {
            get {
                return ResourceManager.GetString("CORR_0405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0406 {
            get {
                return ResourceManager.GetString("CORR_0406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 加速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0407 {
            get {
                return ResourceManager.GetString("CORR_0407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 速度切替長さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0408 {
            get {
                return ResourceManager.GetString("CORR_0408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 速度(速度切替) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0409 {
            get {
                return ResourceManager.GetString("CORR_0409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 加速度(速度切替) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_040A {
            get {
                return ResourceManager.GetString("CORR_040A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No1前後 原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0501 {
            get {
                return ResourceManager.GetString("CORR_0501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No1前後 圧着オフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0502 {
            get {
                return ResourceManager.GetString("CORR_0502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No1前後 速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0503 {
            get {
                return ResourceManager.GetString("CORR_0503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No1前後 加速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0504 {
            get {
                return ResourceManager.GetString("CORR_0504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2前後 原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0605 {
            get {
                return ResourceManager.GetString("CORR_0605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2前後 圧着オフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0606 {
            get {
                return ResourceManager.GetString("CORR_0606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2前後 持替位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0607 {
            get {
                return ResourceManager.GetString("CORR_0607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2前後 先端持替位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0608 {
            get {
                return ResourceManager.GetString("CORR_0608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2前後 速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0609 {
            get {
                return ResourceManager.GetString("CORR_0609", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2前後 加速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_060A {
            get {
                return ResourceManager.GetString("CORR_060A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ1 オフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0701 {
            get {
                return ResourceManager.GetString("CORR_0701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ1 検出オフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0702 {
            get {
                return ResourceManager.GetString("CORR_0702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ2 オフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0703 {
            get {
                return ResourceManager.GetString("CORR_0703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ2 検出オフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0704 {
            get {
                return ResourceManager.GetString("CORR_0704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カット原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0705 {
            get {
                return ResourceManager.GetString("CORR_0705", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カット位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0706 {
            get {
                return ResourceManager.GetString("CORR_0706", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切込み原位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0707 {
            get {
                return ResourceManager.GetString("CORR_0707", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電線ガイド位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0708 {
            get {
                return ResourceManager.GetString("CORR_0708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カット・電線ガイド 速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0709 {
            get {
                return ResourceManager.GetString("CORR_0709", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カット・電線ガイド 加速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_070A {
            get {
                return ResourceManager.GetString("CORR_070A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ 速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_070B {
            get {
                return ResourceManager.GetString("CORR_070B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ 加速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_070C {
            get {
                return ResourceManager.GetString("CORR_070C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着機1 原位置センサ補正 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0801 {
            get {
                return ResourceManager.GetString("CORR_0801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着機2 原位置センサ補正 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0802 {
            get {
                return ResourceManager.GetString("CORR_0802", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着機1速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0803 {
            get {
                return ResourceManager.GetString("CORR_0803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着機1加速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0804 {
            get {
                return ResourceManager.GetString("CORR_0804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着機2速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0805 {
            get {
                return ResourceManager.GetString("CORR_0805", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着機2加速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0806 {
            get {
                return ResourceManager.GetString("CORR_0806", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No1旋回 防水栓挿入位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0901 {
            get {
                return ResourceManager.GetString("CORR_0901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No1旋回 防水栓挿入検出位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0902 {
            get {
                return ResourceManager.GetString("CORR_0902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No1前後 シール挿入開始位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0903 {
            get {
                return ResourceManager.GetString("CORR_0903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No1前後 シール挿入オフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0904 {
            get {
                return ResourceManager.GetString("CORR_0904", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 防水栓挿入位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0905 {
            get {
                return ResourceManager.GetString("CORR_0905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2搬送 防水栓挿入検出位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0906 {
            get {
                return ResourceManager.GetString("CORR_0906", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2前後 シール挿入開始位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0907 {
            get {
                return ResourceManager.GetString("CORR_0907", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No2前後 シール挿入オフセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CORR_0908 {
            get {
                return ResourceManager.GetString("CORR_0908", resourceCulture);
            }
        }
    }
}
