//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap aplibtn {
            get {
                object obj = ResourceManager.GetObject("aplibtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AutoExitBtn {
            get {
                object obj = ResourceManager.GetObject("AutoExitBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap automodebtn {
            get {
                object obj = ResourceManager.GetObject("automodebtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap automodebtn2 {
            get {
                object obj = ResourceManager.GetObject("automodebtn2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blade {
            get {
                object obj = ResourceManager.GetObject("Blade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blade_ajust {
            get {
                object obj = ResourceManager.GetObject("blade_ajust", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bottompanel {
            get {
                object obj = ResourceManager.GetObject("bottompanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CFM {
            get {
                object obj = ResourceManager.GetObject("CFM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseBtn {
            get {
                object obj = ResourceManager.GetObject("CloseBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClosedTerm {
            get {
                object obj = ResourceManager.GetObject("ClosedTerm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClosePanel {
            get {
                object obj = ResourceManager.GetObject("ClosePanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comentpanel {
            get {
                object obj = ResourceManager.GetObject("comentpanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controlpanel {
            get {
                object obj = ResourceManager.GetObject("controlpanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap countdown {
            get {
                object obj = ResourceManager.GetObject("countdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap counterpanel {
            get {
                object obj = ResourceManager.GetObject("counterpanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CountOffBtnDown {
            get {
                object obj = ResourceManager.GetObject("CountOffBtnDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CountOffBtnUp {
            get {
                object obj = ResourceManager.GetObject("CountOffBtnUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap countup {
            get {
                object obj = ResourceManager.GetObject("countup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrimpAOFF {
            get {
                object obj = ResourceManager.GetObject("CrimpAOFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrimpAON {
            get {
                object obj = ResourceManager.GetObject("CrimpAON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrimpBlade {
            get {
                object obj = ResourceManager.GetObject("CrimpBlade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrimpBOFF {
            get {
                object obj = ResourceManager.GetObject("CrimpBOFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crimpBON {
            get {
                object obj = ResourceManager.GetObject("crimpBON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrimpLower {
            get {
                object obj = ResourceManager.GetObject("CrimpLower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrimpUpper {
            get {
                object obj = ResourceManager.GetObject("CrimpUpper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CycleModeBtn {
            get {
                object obj = ResourceManager.GetObject("CycleModeBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownLoadBtn {
            get {
                object obj = ResourceManager.GetObject("DownLoadBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Emblem {
            get {
                object obj = ResourceManager.GetObject("Emblem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap entwire {
            get {
                object obj = ResourceManager.GetObject("entwire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ErrClose {
            get {
                object obj = ResourceManager.GetObject("ErrClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ErrorBase {
            get {
                object obj = ResourceManager.GetObject("ErrorBase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ErrorImage {
            get {
                object obj = ResourceManager.GetObject("ErrorImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ErrorPanel {
            get {
                object obj = ResourceManager.GetObject("ErrorPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ErrorPanel2 {
            get {
                object obj = ResourceManager.GetObject("ErrorPanel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig0_0 {
            get {
                object obj = ResourceManager.GetObject("Fig0_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig1_0 {
            get {
                object obj = ResourceManager.GetObject("Fig1_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig1_1 {
            get {
                object obj = ResourceManager.GetObject("Fig1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig1_3 {
            get {
                object obj = ResourceManager.GetObject("Fig1_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig1_4 {
            get {
                object obj = ResourceManager.GetObject("Fig1_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig1_5 {
            get {
                object obj = ResourceManager.GetObject("Fig1_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig1_7 {
            get {
                object obj = ResourceManager.GetObject("Fig1_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig1_9 {
            get {
                object obj = ResourceManager.GetObject("Fig1_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig2_0 {
            get {
                object obj = ResourceManager.GetObject("Fig2_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig2_1 {
            get {
                object obj = ResourceManager.GetObject("Fig2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig2_3 {
            get {
                object obj = ResourceManager.GetObject("Fig2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig2_4 {
            get {
                object obj = ResourceManager.GetObject("Fig2_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig2_5 {
            get {
                object obj = ResourceManager.GetObject("Fig2_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig2_7 {
            get {
                object obj = ResourceManager.GetObject("Fig2_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fig2_9 {
            get {
                object obj = ResourceManager.GetObject("Fig2_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FigBase {
            get {
                object obj = ResourceManager.GetObject("FigBase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FormIcon {
            get {
                object obj = ResourceManager.GetObject("FormIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HalfAOFF {
            get {
                object obj = ResourceManager.GetObject("HalfAOFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HalfAON {
            get {
                object obj = ResourceManager.GetObject("HalfAON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HalfBOFF {
            get {
                object obj = ResourceManager.GetObject("HalfBOFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HalfBON {
            get {
                object obj = ResourceManager.GetObject("HalfBON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HQCDiplay {
            get {
                object obj = ResourceManager.GetObject("HQCDiplay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InchingBtn {
            get {
                object obj = ResourceManager.GetObject("InchingBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IncingSw {
            get {
                object obj = ResourceManager.GetObject("IncingSw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iomonitorpanel {
            get {
                object obj = ResourceManager.GetObject("iomonitorpanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Jam {
            get {
                object obj = ResourceManager.GetObject("Jam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JAMLogo {
            get {
                object obj = ResourceManager.GetObject("JAMLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JAMLogo2 {
            get {
                object obj = ResourceManager.GetObject("JAMLogo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JogModeBtn {
            get {
                object obj = ResourceManager.GetObject("JogModeBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Led {
            get {
                object obj = ResourceManager.GetObject("Led", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LedBlueOff {
            get {
                object obj = ResourceManager.GetObject("LedBlueOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LedBlueOn {
            get {
                object obj = ResourceManager.GetObject("LedBlueOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LedGreenOff {
            get {
                object obj = ResourceManager.GetObject("LedGreenOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LedGreenOn {
            get {
                object obj = ResourceManager.GetObject("LedGreenOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LedRed {
            get {
                object obj = ResourceManager.GetObject("LedRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LedRedOff {
            get {
                object obj = ResourceManager.GetObject("LedRedOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LedRedOn {
            get {
                object obj = ResourceManager.GetObject("LedRedOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo1 {
            get {
                object obj = ResourceManager.GetObject("logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap machinestationimage {
            get {
                object obj = ResourceManager.GetObject("machinestationimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon mainIcon {
            get {
                object obj = ResourceManager.GetObject("mainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainPanel {
            get {
                object obj = ResourceManager.GetObject("MainPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MicroMeter {
            get {
                object obj = ResourceManager.GetObject("MicroMeter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MiniLedBlueOff {
            get {
                object obj = ResourceManager.GetObject("MiniLedBlueOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MiniLedBlueOffDark {
            get {
                object obj = ResourceManager.GetObject("MiniLedBlueOffDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MiniLedBlueOn {
            get {
                object obj = ResourceManager.GetObject("MiniLedBlueOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MiniLedGreenOff {
            get {
                object obj = ResourceManager.GetObject("MiniLedGreenOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MiniLedGreenOn {
            get {
                object obj = ResourceManager.GetObject("MiniLedGreenOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MiniLedRedOff {
            get {
                object obj = ResourceManager.GetObject("MiniLedRedOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MiniLedRedOn {
            get {
                object obj = ResourceManager.GetObject("MiniLedRedOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ModeBtn {
            get {
                object obj = ResourceManager.GetObject("ModeBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NextScadule {
            get {
                object obj = ResourceManager.GetObject("NextScadule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ONLINE {
            get {
                object obj = ResourceManager.GetObject("ONLINE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap origin {
            get {
                object obj = ResourceManager.GetObject("origin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap origin2 {
            get {
                object obj = ResourceManager.GetObject("origin2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap origin3 {
            get {
                object obj = ResourceManager.GetObject("origin3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap origin31 {
            get {
                object obj = ResourceManager.GetObject("origin31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panelbase {
            get {
                object obj = ResourceManager.GetObject("panelbase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIC0013 {
            get {
                object obj = ResourceManager.GetObject("PIC0013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIC0017 {
            get {
                object obj = ResourceManager.GetObject("PIC0017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PIC0018 {
            get {
                object obj = ResourceManager.GetObject("PIC0018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Promaster {
            get {
                object obj = ResourceManager.GetObject("Promaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ResetBtn {
            get {
                object obj = ResourceManager.GetObject("ResetBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RialSeal {
            get {
                object obj = ResourceManager.GetObject("RialSeal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RialSeal1 {
            get {
                object obj = ResourceManager.GetObject("RialSeal1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RialSeal2 {
            get {
                object obj = ResourceManager.GetObject("RialSeal2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SealAOFF {
            get {
                object obj = ResourceManager.GetObject("SealAOFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SealAON {
            get {
                object obj = ResourceManager.GetObject("SealAON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SealBOFF {
            get {
                object obj = ResourceManager.GetObject("SealBOFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SealBON {
            get {
                object obj = ResourceManager.GetObject("SealBON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sensorpanel {
            get {
                object obj = ResourceManager.GetObject("sensorpanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SIDEPANEL {
            get {
                object obj = ResourceManager.GetObject("SIDEPANEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlowMode1Btn {
            get {
                object obj = ResourceManager.GetObject("SlowMode1Btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StaffRoll {
            get {
                object obj = ResourceManager.GetObject("StaffRoll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StandardBtn {
            get {
                object obj = ResourceManager.GetObject("StandardBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StartBtn {
            get {
                object obj = ResourceManager.GetObject("StartBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopBtn {
            get {
                object obj = ResourceManager.GetObject("StopBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StripA {
            get {
                object obj = ResourceManager.GetObject("StripA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StripAOFF {
            get {
                object obj = ResourceManager.GetObject("StripAOFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StripAON {
            get {
                object obj = ResourceManager.GetObject("StripAON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StripBOFF {
            get {
                object obj = ResourceManager.GetObject("StripBOFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StripBON {
            get {
                object obj = ResourceManager.GetObject("StripBON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap systempanel {
            get {
                object obj = ResourceManager.GetObject("systempanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap systempanel2 {
            get {
                object obj = ResourceManager.GetObject("systempanel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap systempanel3 {
            get {
                object obj = ResourceManager.GetObject("systempanel3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TenKeyDisp {
            get {
                object obj = ResourceManager.GetObject("TenKeyDisp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TenKeyEnter {
            get {
                object obj = ResourceManager.GetObject("TenKeyEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TenKeyMain {
            get {
                object obj = ResourceManager.GetObject("TenKeyMain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TermDataSetPanel {
            get {
                object obj = ResourceManager.GetObject("TermDataSetPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TerminalFlag {
            get {
                object obj = ResourceManager.GetObject("TerminalFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Test {
            get {
                object obj = ResourceManager.GetObject("Test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TInchingBtn {
            get {
                object obj = ResourceManager.GetObject("TInchingBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap title1 {
            get {
                object obj = ResourceManager.GetObject("title1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap titleSH2 {
            get {
                object obj = ResourceManager.GetObject("titleSH2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOPBAR {
            get {
                object obj = ResourceManager.GetObject("TOPBAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tweakpanel {
            get {
                object obj = ResourceManager.GetObject("tweakpanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlockcrimpA {
            get {
                object obj = ResourceManager.GetObject("unitlockcrimpA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlockcrimpA2 {
            get {
                object obj = ResourceManager.GetObject("unitlockcrimpA2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlockcrimpB {
            get {
                object obj = ResourceManager.GetObject("unitlockcrimpB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlockcrimpB2 {
            get {
                object obj = ResourceManager.GetObject("unitlockcrimpB2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlockhalfA {
            get {
                object obj = ResourceManager.GetObject("unitlockhalfA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlockhalfA2 {
            get {
                object obj = ResourceManager.GetObject("unitlockhalfA2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlockhalfB {
            get {
                object obj = ResourceManager.GetObject("unitlockhalfB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlockhalfB2 {
            get {
                object obj = ResourceManager.GetObject("unitlockhalfB2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlocksealA {
            get {
                object obj = ResourceManager.GetObject("unitlocksealA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlocksealA3 {
            get {
                object obj = ResourceManager.GetObject("unitlocksealA3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlocksealB {
            get {
                object obj = ResourceManager.GetObject("unitlocksealB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlocksealB3 {
            get {
                object obj = ResourceManager.GetObject("unitlocksealB3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlockstripA {
            get {
                object obj = ResourceManager.GetObject("unitlockstripA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitlockstripB {
            get {
                object obj = ResourceManager.GetObject("unitlockstripB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitpanel {
            get {
                object obj = ResourceManager.GetObject("unitpanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitSeal1 {
            get {
                object obj = ResourceManager.GetObject("unitSeal1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unitSeal2 {
            get {
                object obj = ResourceManager.GetObject("unitSeal2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpLoadBtn {
            get {
                object obj = ResourceManager.GetObject("UpLoadBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VerSionPanel {
            get {
                object obj = ResourceManager.GetObject("VerSionPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VirtualSeal {
            get {
                object obj = ResourceManager.GetObject("VirtualSeal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VirtualSeal1 {
            get {
                object obj = ResourceManager.GetObject("VirtualSeal1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VirtualSeal2 {
            get {
                object obj = ResourceManager.GetObject("VirtualSeal2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WireGraph {
            get {
                object obj = ResourceManager.GetObject("WireGraph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wireprocess {
            get {
                object obj = ResourceManager.GetObject("wireprocess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WireSizeG {
            get {
                object obj = ResourceManager.GetObject("WireSizeG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkImage {
            get {
                object obj = ResourceManager.GetObject("WorkImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkImage_050411 {
            get {
                object obj = ResourceManager.GetObject("WorkImage_050411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkImage_050422 {
            get {
                object obj = ResourceManager.GetObject("WorkImage_050422", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkImage_050422_2 {
            get {
                object obj = ResourceManager.GetObject("WorkImage_050422_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkImage_old {
            get {
                object obj = ResourceManager.GetObject("WorkImage_old", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap workparambase {
            get {
                object obj = ResourceManager.GetObject("workparambase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap worlparamcover {
            get {
                object obj = ResourceManager.GetObject("worlparamcover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
