//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScreenMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScreenMsg() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.Properties.ScreenMsg", typeof(ScreenMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   E_カットストリップ上:原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0000 {
            get {
                return ResourceManager.GetString("ERR_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_カットストリップ下:原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0001 {
            get {
                return ResourceManager.GetString("ERR_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_排出: 原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0002 {
            get {
                return ResourceManager.GetString("ERR_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_フィード: サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0003 {
            get {
                return ResourceManager.GetString("ERR_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_No１前後:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0004 {
            get {
                return ResourceManager.GetString("ERR_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_旋回:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0005 {
            get {
                return ResourceManager.GetString("ERR_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着機１:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0006 {
            get {
                return ResourceManager.GetString("ERR_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_No2前後:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0007 {
            get {
                return ResourceManager.GetString("ERR_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0008 {
            get {
                return ResourceManager.GetString("ERR_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_フィード:原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0009 {
            get {
                return ResourceManager.GetString("ERR_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_No1前後:原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_000A {
            get {
                return ResourceManager.GetString("ERR_000A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_旋回:原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_000B {
            get {
                return ResourceManager.GetString("ERR_000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着機1:原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_000C {
            get {
                return ResourceManager.GetString("ERR_000C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_No2前後:原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_000D {
            get {
                return ResourceManager.GetString("ERR_000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_搬送:原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_000E {
            get {
                return ResourceManager.GetString("ERR_000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着機2:原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_000F {
            get {
                return ResourceManager.GetString("ERR_000F", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0010 {
            get {
                return ResourceManager.GetString("ERR_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0011 {
            get {
                return ResourceManager.GetString("ERR_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_電線無し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0012 {
            get {
                return ResourceManager.GetString("ERR_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_電線過負荷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0013 {
            get {
                return ResourceManager.GetString("ERR_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_継ぎ目ワイヤー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0014 {
            get {
                return ResourceManager.GetString("ERR_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_継ぎ目予告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0015 {
            get {
                return ResourceManager.GetString("ERR_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_ジョイント作業 [標準] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0016 {
            get {
                return ResourceManager.GetString("ERR_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_ジョイント作業 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0017 {
            get {
                return ResourceManager.GetString("ERR_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_搬送:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0018 {
            get {
                return ResourceManager.GetString("ERR_0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着機2:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0019 {
            get {
                return ResourceManager.GetString("ERR_0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_カットストリップ上:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_001A {
            get {
                return ResourceManager.GetString("ERR_001A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_カットストリップ下:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_001B {
            get {
                return ResourceManager.GetString("ERR_001B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_排出:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_001C {
            get {
                return ResourceManager.GetString("ERR_001C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_非常停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_001D {
            get {
                return ResourceManager.GetString("ERR_001D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_ベルトシューター異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_001E {
            get {
                return ResourceManager.GetString("ERR_001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_空圧低下 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_001F {
            get {
                return ResourceManager.GetString("ERR_001F", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0020 {
            get {
                return ResourceManager.GetString("ERR_0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_ストリップミス1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0021 {
            get {
                return ResourceManager.GetString("ERR_0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着ミス1(ファイバー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0022 {
            get {
                return ResourceManager.GetString("ERR_0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_ストリップ1検出センサー異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0023 {
            get {
                return ResourceManager.GetString("ERR_0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着1検出センサー異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0024 {
            get {
                return ResourceManager.GetString("ERR_0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_端子無し1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0025 {
            get {
                return ResourceManager.GetString("ERR_0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_端子過負荷1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0026 {
            get {
                return ResourceManager.GetString("ERR_0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_シール無し1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0027 {
            get {
                return ResourceManager.GetString("ERR_0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_フィード偏差異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0028 {
            get {
                return ResourceManager.GetString("ERR_0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧力管理判定遅延 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0029 {
            get {
                return ResourceManager.GetString("ERR_0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_スーパーバイザーモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_002A {
            get {
                return ResourceManager.GetString("ERR_002A", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_002B {
            get {
                return ResourceManager.GetString("ERR_002B", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_002C {
            get {
                return ResourceManager.GetString("ERR_002C", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_002D {
            get {
                return ResourceManager.GetString("ERR_002D", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_002E {
            get {
                return ResourceManager.GetString("ERR_002E", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_002F {
            get {
                return ResourceManager.GetString("ERR_002F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_ストリップミス2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0030 {
            get {
                return ResourceManager.GetString("ERR_0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着ミス2 (ファイバー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0031 {
            get {
                return ResourceManager.GetString("ERR_0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_ストリップ2 検出センサー異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0032 {
            get {
                return ResourceManager.GetString("ERR_0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着2 検出センサー異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0033 {
            get {
                return ResourceManager.GetString("ERR_0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_端子無し2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0034 {
            get {
                return ResourceManager.GetString("ERR_0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_端子過負荷2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0035 {
            get {
                return ResourceManager.GetString("ERR_0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_シール無し2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0036 {
            get {
                return ResourceManager.GetString("ERR_0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_シール挿入ミス2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0037 {
            get {
                return ResourceManager.GetString("ERR_0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_シール挿入ミス1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0038 {
            get {
                return ResourceManager.GetString("ERR_0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_１側チャック開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0039 {
            get {
                return ResourceManager.GetString("ERR_0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_シール1空送ミス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_003A {
            get {
                return ResourceManager.GetString("ERR_003A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_シールチェック1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_003B {
            get {
                return ResourceManager.GetString("ERR_003B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_挿入検出1センサー異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_003C {
            get {
                return ResourceManager.GetString("ERR_003C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_シール前後1センサー異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_003D {
            get {
                return ResourceManager.GetString("ERR_003D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_防水通過センサー異常1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_003E {
            get {
                return ResourceManager.GetString("ERR_003E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_叩き棒を外して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_003F {
            get {
                return ResourceManager.GetString("ERR_003F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_バッテリ電圧低下 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0040 {
            get {
                return ResourceManager.GetString("ERR_0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_防水1センサー異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0041 {
            get {
                return ResourceManager.GetString("ERR_0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_ストリップ1ティーチング処理中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0042 {
            get {
                return ResourceManager.GetString("ERR_0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_ストリップ2ティーチング処理中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0043 {
            get {
                return ResourceManager.GetString("ERR_0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_挿入検出1センサー異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0044 {
            get {
                return ResourceManager.GetString("ERR_0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_排出カバーオープン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0045 {
            get {
                return ResourceManager.GetString("ERR_0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_ワイヤーガイドを交換して下さい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0046 {
            get {
                return ResourceManager.GetString("ERR_0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_フィードローラ開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0047 {
            get {
                return ResourceManager.GetString("ERR_0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_2側チャック開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0048 {
            get {
                return ResourceManager.GetString("ERR_0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_シール2空送ミス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0049 {
            get {
                return ResourceManager.GetString("ERR_0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_シールチェック2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_004A {
            get {
                return ResourceManager.GetString("ERR_004A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_挿入検出2センサー異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_004B {
            get {
                return ResourceManager.GetString("ERR_004B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_シール前後2センサー異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_004C {
            get {
                return ResourceManager.GetString("ERR_004C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_防水通過センサー異常2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_004D {
            get {
                return ResourceManager.GetString("ERR_004D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_不良品排出前停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_004E {
            get {
                return ResourceManager.GetString("ERR_004E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_叩き棒をセットして下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_004F {
            get {
                return ResourceManager.GetString("ERR_004F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着インチングSWを解除して下さい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0050 {
            get {
                return ResourceManager.GetString("ERR_0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0051 {
            get {
                return ResourceManager.GetString("ERR_0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0052 {
            get {
                return ResourceManager.GetString("ERR_0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_No1沈み:　原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0053 {
            get {
                return ResourceManager.GetString("ERR_0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_No2沈み:　原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0054 {
            get {
                return ResourceManager.GetString("ERR_0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_オートクリンプハイト1: 原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0055 {
            get {
                return ResourceManager.GetString("ERR_0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_オートクリンプハイト2: 原点復帰異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0056 {
            get {
                return ResourceManager.GetString("ERR_0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_No1沈み:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0057 {
            get {
                return ResourceManager.GetString("ERR_0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_ティーチング電線を排出してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0058 {
            get {
                return ResourceManager.GetString("ERR_0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着ミス1 (CFM) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0059 {
            get {
                return ResourceManager.GetString("ERR_0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着ミス2 (CFM) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_005A {
            get {
                return ResourceManager.GetString("ERR_005A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_オートクリンプハイト1: サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_005B {
            get {
                return ResourceManager.GetString("ERR_005B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_オートクリンプハイト2: サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_005C {
            get {
                return ResourceManager.GetString("ERR_005C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_排出ユニットを元に戻してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_005D {
            get {
                return ResourceManager.GetString("ERR_005D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_カバーオープン（旋回） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_005E {
            get {
                return ResourceManager.GetString("ERR_005E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_カバーオープン（搬送） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_005F {
            get {
                return ResourceManager.GetString("ERR_005F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧力管理装置が認識されません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0060 {
            get {
                return ResourceManager.GetString("ERR_0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧力管理装置のアラーム異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0061 {
            get {
                return ResourceManager.GetString("ERR_0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_先出長さ変更のため、現在のストリップ１長では不適切です、設定値を見直して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0062 {
            get {
                return ResourceManager.GetString("ERR_0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_先出長さ変更のため、現在のハーフストリップ1では不適切です、設定値を見直して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0063 {
            get {
                return ResourceManager.GetString("ERR_0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_先出長さ変更のため、現在の圧着１位置では不適切です、設定値を見直して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0064 {
            get {
                return ResourceManager.GetString("ERR_0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_先出長さ変更のため、現在のストリップ２長では不適切です、設定値を見直して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0065 {
            get {
                return ResourceManager.GetString("ERR_0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_先出長さ変更のため、現在のハーフストリップ２では不適切です、設定値を見直して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0066 {
            get {
                return ResourceManager.GetString("ERR_0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_先出長さ変更のため、現在の圧着２位置では不適切です、設定値を見直して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0067 {
            get {
                return ResourceManager.GetString("ERR_0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_No2沈み:サーボアラーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0068 {
            get {
                return ResourceManager.GetString("ERR_0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0069 {
            get {
                return ResourceManager.GetString("ERR_0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着機1を原位置に戻してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_006A {
            get {
                return ResourceManager.GetString("ERR_006A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着機2を原位置に戻してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_006B {
            get {
                return ResourceManager.GetString("ERR_006B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着機1の手動ハンドルを外してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_006C {
            get {
                return ResourceManager.GetString("ERR_006C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着機2の手動ハンドルを外してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_006D {
            get {
                return ResourceManager.GetString("ERR_006D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_No2検出前後位置(センサー)エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_006E {
            get {
                return ResourceManager.GetString("ERR_006E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_排出ユニットを元に戻してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_006F {
            get {
                return ResourceManager.GetString("ERR_006F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_原位置復帰中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0070 {
            get {
                return ResourceManager.GetString("ERR_0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_設定本数完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0071 {
            get {
                return ResourceManager.GetString("ERR_0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_設定ロット完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0072 {
            get {
                return ResourceManager.GetString("ERR_0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_電線を排出します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0073 {
            get {
                return ResourceManager.GetString("ERR_0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_電線をティーチングします に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0074 {
            get {
                return ResourceManager.GetString("ERR_0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着機１原位置復帰中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0075 {
            get {
                return ResourceManager.GetString("ERR_0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_圧着機２原位置復帰中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0076 {
            get {
                return ResourceManager.GetString("ERR_0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_スタートスイッチを押して下さい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0077 {
            get {
                return ResourceManager.GetString("ERR_0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_１側先端ノズルの位置を変更してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0078 {
            get {
                return ResourceManager.GetString("ERR_0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_ワイヤフィードのチューブを変更してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0079 {
            get {
                return ResourceManager.GetString("ERR_0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_原位置復帰中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0100 {
            get {
                return ResourceManager.GetString("ERR_0100", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0101 {
            get {
                return ResourceManager.GetString("ERR_0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0102 {
            get {
                return ResourceManager.GetString("ERR_0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0103 {
            get {
                return ResourceManager.GetString("ERR_0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0104 {
            get {
                return ResourceManager.GetString("ERR_0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0105 {
            get {
                return ResourceManager.GetString("ERR_0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0106 {
            get {
                return ResourceManager.GetString("ERR_0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0107 {
            get {
                return ResourceManager.GetString("ERR_0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0108 {
            get {
                return ResourceManager.GetString("ERR_0108", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0109 {
            get {
                return ResourceManager.GetString("ERR_0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_010A {
            get {
                return ResourceManager.GetString("ERR_010A", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_010B {
            get {
                return ResourceManager.GetString("ERR_010B", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_010C {
            get {
                return ResourceManager.GetString("ERR_010C", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_010D {
            get {
                return ResourceManager.GetString("ERR_010D", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_010E {
            get {
                return ResourceManager.GetString("ERR_010E", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_010F {
            get {
                return ResourceManager.GetString("ERR_010F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_通信切断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0110 {
            get {
                return ResourceManager.GetString("ERR_0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0111 {
            get {
                return ResourceManager.GetString("ERR_0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0112 {
            get {
                return ResourceManager.GetString("ERR_0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_0113 {
            get {
                return ResourceManager.GetString("ERR_0113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0001 {
            get {
                return ResourceManager.GetString("SYS_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0002 {
            get {
                return ResourceManager.GetString("SYS_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0003 {
            get {
                return ResourceManager.GetString("SYS_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリケーションの多重起動は行えません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0004 {
            get {
                return ResourceManager.GetString("SYS_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本アプリケーションをリモートセッションから起動することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0005 {
            get {
                return ResourceManager.GetString("SYS_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモリ割当データの機種名が前回起動時と異なります。
        ///このまま起動を続けてもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0006 {
            get {
                return ResourceManager.GetString("SYS_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動機のデータが初期化されていません。初期化してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0007 {
            get {
                return ResourceManager.GetString("SYS_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対応するワークIDが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0008 {
            get {
                return ResourceManager.GetString("SYS_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アドレスの範囲が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0009 {
            get {
                return ResourceManager.GetString("SYS_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの長さが不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000A {
            get {
                return ResourceManager.GetString("SYS_000A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が適正範囲ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000B {
            get {
                return ResourceManager.GetString("SYS_000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バンクデータをデフォルト値で補いました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000C {
            get {
                return ResourceManager.GetString("SYS_000C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム設定ファイルへのアクセスに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000D {
            get {
                return ResourceManager.GetString("SYS_000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモリ割当データファイルへのアクセスに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000E {
            get {
                return ResourceManager.GetString("SYS_000E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バンクデータファイルへのアクセスに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_000F {
            get {
                return ResourceManager.GetString("SYS_000F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   補正値ファイルへのアクセスに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0010 {
            get {
                return ResourceManager.GetString("SYS_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0011 {
            get {
                return ResourceManager.GetString("SYS_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードとパスワード（確認）の値が異なります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0012 {
            get {
                return ResourceManager.GetString("SYS_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム設定を行いました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0013 {
            get {
                return ResourceManager.GetString("SYS_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バンクデータ値範囲外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0014 {
            get {
                return ResourceManager.GetString("SYS_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バンクデータがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0015 {
            get {
                return ResourceManager.GetString("SYS_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}以上の値を入力して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0016 {
            get {
                return ResourceManager.GetString("SYS_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対応するWORKIDが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0017 {
            get {
                return ResourceManager.GetString("SYS_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}に値が入力されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0018 {
            get {
                return ResourceManager.GetString("SYS_0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}のフォーマットが不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0019 {
            get {
                return ResourceManager.GetString("SYS_0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は、{1}から{2}の範囲で入力を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001A {
            get {
                return ResourceManager.GetString("SYS_001A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は、{1}以上の値かつ、{2}未満の値を入力して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001B {
            get {
                return ResourceManager.GetString("SYS_001B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動機との同期が行われていないため、操作を行うことができません。
        ///自動機に接続を行ってから操作を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001C {
            get {
                return ResourceManager.GetString("SYS_001C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ONLINE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001D {
            get {
                return ResourceManager.GetString("SYS_001D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFFLINE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001E {
            get {
                return ResourceManager.GetString("SYS_001E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   のバージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_001F {
            get {
                return ResourceManager.GetString("SYS_001F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_0020 {
            get {
                return ResourceManager.GetString("SYS_0020", resourceCulture);
            }
        }
    }
}
