//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkDataMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkDataMsg() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.Properties.WorkDataMsg", typeof(WorkDataMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   切断長 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0101 {
            get {
                return ResourceManager.GetString("WORK_0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   先出し長さ1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0105 {
            get {
                return ResourceManager.GetString("WORK_0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   先出し長さ2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0106 {
            get {
                return ResourceManager.GetString("WORK_0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0201 {
            get {
                return ResourceManager.GetString("WORK_0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハーフストリップ1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0202 {
            get {
                return ResourceManager.GetString("WORK_0202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ深さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0203 {
            get {
                return ResourceManager.GetString("WORK_0203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリッププルバック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0204 {
            get {
                return ResourceManager.GetString("WORK_0204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0301 {
            get {
                return ResourceManager.GetString("WORK_0301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハーフストリップ2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0302 {
            get {
                return ResourceManager.GetString("WORK_0302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリップ深さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0303 {
            get {
                return ResourceManager.GetString("WORK_0303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ストリッププルバック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0304 {
            get {
                return ResourceManager.GetString("WORK_0304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着位置1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0401 {
            get {
                return ResourceManager.GetString("WORK_0401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリンプハイト1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0402 {
            get {
                return ResourceManager.GetString("WORK_0402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   沈み1補正時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0403 {
            get {
                return ResourceManager.GetString("WORK_0403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着安定時間1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0404 {
            get {
                return ResourceManager.GetString("WORK_0404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PFM番号1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0405 {
            get {
                return ResourceManager.GetString("WORK_0405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着1横位置補正 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0406 {
            get {
                return ResourceManager.GetString("WORK_0406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着1後退位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0407 {
            get {
                return ResourceManager.GetString("WORK_0407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着位置2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0501 {
            get {
                return ResourceManager.GetString("WORK_0501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリンプハイト2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0502 {
            get {
                return ResourceManager.GetString("WORK_0502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   沈み2補正時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0503 {
            get {
                return ResourceManager.GetString("WORK_0503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着安定時間2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0504 {
            get {
                return ResourceManager.GetString("WORK_0504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PFM番号2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0505 {
            get {
                return ResourceManager.GetString("WORK_0505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   圧着2横位置補正 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0506 {
            get {
                return ResourceManager.GetString("WORK_0506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水1挿入量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0601 {
            get {
                return ResourceManager.GetString("WORK_0601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水1戻り量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0602 {
            get {
                return ResourceManager.GetString("WORK_0602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水1挿入速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0603 {
            get {
                return ResourceManager.GetString("WORK_0603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水1挿入加速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0604 {
            get {
                return ResourceManager.GetString("WORK_0604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水1 F線ガイド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0605 {
            get {
                return ResourceManager.GetString("WORK_0605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水2挿入量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0701 {
            get {
                return ResourceManager.GetString("WORK_0701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水2戻り量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0702 {
            get {
                return ResourceManager.GetString("WORK_0702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水2挿入速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0703 {
            get {
                return ResourceManager.GetString("WORK_0703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水2挿入加速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0704 {
            get {
                return ResourceManager.GetString("WORK_0704", resourceCulture);
            }
        }
        
        /// <summary>
        ///   防水2 F線ガイド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0705 {
            get {
                return ResourceManager.GetString("WORK_0705", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロット設定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0806 {
            get {
                return ResourceManager.GetString("WORK_0806", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QTY設定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0807 {
            get {
                return ResourceManager.GetString("WORK_0807", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tact1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0808 {
            get {
                return ResourceManager.GetString("WORK_0808", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tack2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0809 {
            get {
                return ResourceManager.GetString("WORK_0809", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tack3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_080A {
            get {
                return ResourceManager.GetString("WORK_080A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動復帰時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0901 {
            get {
                return ResourceManager.GetString("WORK_0901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイクル係数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0902 {
            get {
                return ResourceManager.GetString("WORK_0902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィード速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A01 {
            get {
                return ResourceManager.GetString("WORK_0A01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィード加速時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A02 {
            get {
                return ResourceManager.GetString("WORK_0A02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切断長補正値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A03 {
            get {
                return ResourceManager.GetString("WORK_0A03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィード速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A04 {
            get {
                return ResourceManager.GetString("WORK_0A04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィード加速時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A05 {
            get {
                return ResourceManager.GetString("WORK_0A05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切断長補正値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A06 {
            get {
                return ResourceManager.GetString("WORK_0A06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィード速度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A07 {
            get {
                return ResourceManager.GetString("WORK_0A07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィード加速時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A08 {
            get {
                return ResourceManager.GetString("WORK_0A08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切断長補正値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A09 {
            get {
                return ResourceManager.GetString("WORK_0A09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィード切替閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A0A {
            get {
                return ResourceManager.GetString("WORK_0A0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィード切替閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WORK_0A0B {
            get {
                return ResourceManager.GetString("WORK_0A0B", resourceCulture);
            }
        }
    }
}
